config/routes.rb
Rails.application.routes.draw do
  get "welcome/search"
  post "welcome/song"
  resources :pics
  resources :newscores do
   member do
    get "seescore"
    get "createscore"
    get "addpic"
   end
  end
  resources :fragments do
   member do
    get "createscore"
    get "seescore"
   end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "fragments#index"
end

app/models/pic.rb
class Pic < ApplicationRecord

def mypic=(uploaded_io)
File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
  file.write(uploaded_io.read)
end
write_attribute(:mypic, uploaded_io.original_filename)
end
def mypic
read_attribute(:mypic)
end

end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: %i[ show edit update destroy ]

  # GET /pics or /pics.json
  def index
    @pics = Pic.all
  end

  # GET /pics/1 or /pics/1.json
  def show
  end

  # GET /pics/new
  def new
    @pic = Pic.new
  end

  # GET /pics/1/edit
  def edit
  end

  # POST /pics or /pics.json
  def create
    @pic = Pic.new(pic_params)

    respond_to do |format|
      if @pic.save
        format.html { redirect_to @pic, notice: "Pic was successfully created." }
        format.json { render :show, status: :created, location: @pic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pics/1 or /pics/1.json
  def update
    respond_to do |format|
      if @pic.update(pic_params)
        format.html { redirect_to @pic, notice: "Pic was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @pic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1 or /pics/1.json
  def destroy
    @pic.destroy!

    respond_to do |format|
      format.html { redirect_to pics_path, notice: "Pic was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def pic_params
      params.expect(pic: [ :newscore_id, :mypic ])
    end
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/pics/_form.html.erb
<%= form_with(model: pic) do |form| %>
  <% if pic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
        <% pic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :newscore_id, style: "display: block" %>
    <%= form.number_field :newscore_id %>
  </div>

  <div>
    <%= form.label :mypic, style: "display: block" %>
    <%= form.text_field :mypic %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pics/_pic.html.erb
<div id="<%= dom_id pic %>">
  <p>
    <strong>Newscore:</strong>
    <%= pic.newscore_id %>
  </p>

  <p>
    <strong>Mypic:</strong>
    <%= pic.mypic %>
  </p>

</div>

app/views/pics/edit.html.erb
<% content_for :title, "Editing pic" %>

<h1>Editing pic</h1>

<%= render "form", pic: @pic %>

<br>

<div>
  <%= link_to "Show this pic", @pic %> |
  <%= link_to "Back to pics", pics_path %>
</div>

app/views/pics/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Pics" %>

<h1>Pics</h1>

<div id="pics">
  <% @pics.each do |pic| %>
    <%= render pic %>
    <p>
      <%= link_to "Show this pic", pic %>
    </p>
  <% end %>
</div>

<%= link_to "New pic", new_pic_path %>

app/views/pics/new.html.erb
<% content_for :title, "New pic" %>

<h1>New pic</h1>

<%= render "form", pic: @pic %>

<br>

<div>
  <%= link_to "Back to pics", pics_path %>
</div>

app/views/pics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pic %>

<div>
  <%= link_to "Edit this pic", edit_pic_path(@pic) %> |
  <%= link_to "Back to pics", pics_path %>

  <%= button_to "Destroy this pic", @pic, method: :delete %>
</div>