config/routes.rb
Rails.application.routes.draw do
  get "welcome/search"
  post "welcome/song"
  resources :pics
  resources :newscores do
   member do
    get "seescore"
    get "createscore"
    get "addpic"
   end
  end
  resources :fragments do
   member do
    get "createscore"
    get "seescore"
   end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "fragments#index"
end

app/models/newscore.rb
class Newscore < ApplicationRecord
has_one :pic
accepts_nested_attributes_for :pic
def key_signature=(hey)
write_attribute(:key_signature, hey.downcase.gsub("♯", "is").gsub("♭", "es"))
end
def time_signature=(hey)
write_attribute(:time_signature, hey.downcase.gsub(" beats per bar", "/4"))
end
def metronomemark=(hey)
if hey.include?("BPM")
x=hey.gsub(" BPM", "")
write_attribute(:metronomemark, "4 = "+x.strip.squish)
else
write_attribute(:metronomemark, hey)
end

end

def getmyscore
@score="

      <lilypond staffsize=26>

\\header { 

title = \\markup \"#{title}\"
composer = \\markup \"#{composer}\"

 }

dyn =
\#(make-dynamic-script \#{ \\markup \\text \"#{dynamictext}\" \#})

\\markup \\box \"#{toplevelmarkup}\"

\\score {
  <<
    \\new ChordNames
    \\with {
      majorSevenSymbol = \\markup \"#{cmajorsevensymbol}\"
    }
    \\chordmode { #{accord}1:maj7 }
    \\new StafStafff = \"newviolin\" {
      \\key #{key_signature.split(" ")[0]} \\#{key_signature.split(" ")[1]}
      \\numericTimeSignature
      \\time #{time_signature}
      \\tempo \\markup \"#{metronomemark}\"
      \\textMark \"#{textmark}\"
      \\once \\override TupletNumber.text =
        \\markup \"#{tuplenumber}\"
      #{myscore}
      \\tuplet 3/2 {
        \\once \\override NoteHead.stencil =
          \#ly:text-interface::print
        \\once \\override NoteHead.text =
          \\markup \\lower \#0.5 \"#{notehead}\"
        c''8^\\markup \\italic \"#{testscript}\"
        a'\\finger \\markup \\text \"#{fingering}\"
        \\once \\override Rest.stencil =
          \#(lambda (grob)
             (grob-interpret-markup grob \#{
               \\markup  \"#{rest}\"
               \#}))
        r
      }
    }
    \\new Lyrics \\lyricmode {
      \\markup \\smallCaps \"#{lyrictext}\" 1
    }
    \\new Dynamics { s1\\dyn }
  >>
}
      </lilypond>
      " 
      @score

end
end

app/controllers/newscores_controller.rb
class NewscoresController < ApplicationController
  before_action :set_newscore, only: %i[ show edit update destroy createscore addpic seescore]

  def seescore
      hi=(@newscore.title+@newscore.id.to_s).parameterize
      @hi=hi
      render :createscore
  end
  def createscore

      @score=@newscore.getmyscore
      p @score
      
      wow="./public/uploads/"
      hi=(@newscore.title+@newscore.id.to_s).parameterize
      @hi=hi
      p wow+hi
      File.write(wow+"hey"+hi+".html", @score)
      @hey=`(cd #{wow} && lilypond-book hey#{hi}.html -f html --output #{hi})`

  end
  # GET /newscores or /newscores.json
  def index
    @newscores = Newscore.all
  end

  # GET /newscores/1 or /newscores/1.json
  def show
  end

  # GET /newscores/new
  def new
    @newscore = Newscore.new
  end

  # GET /newscores/1/edit
  def edit
  end
  def addpic
     @newscore.pic=Pic.new
     render :edit
  end

  # POST /newscores or /newscores.json
  def create
    @newscore = Newscore.new(newscore_params)

    respond_to do |format|
      if @newscore.save
        format.html { redirect_to @newscore, notice: "Newscore was successfully created." }
        format.json { render :show, status: :created, location: @newscore }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @newscore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newscores/1 or /newscores/1.json
  def update
    respond_to do |format|
      if @newscore.update(newscore_params)
        format.html { redirect_to @newscore, notice: "Newscore was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @newscore }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @newscore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newscores/1 or /newscores/1.json
  def destroy
    @newscore.destroy!

    respond_to do |format|
      format.html { redirect_to newscores_path, notice: "Newscore was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newscore
      @newscore = Newscore.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def newscore_params
      params.expect(newscore: [ :title, :composer, :toplevelmarkup, :metronomemark, :textmark, :cmajorsevensymbol, :testscript, :notehead, :fingering, :notehead, :rest, :tuplenumber, :lyrictext, :dynamictext, :key_signature, :time_signature, :accord, :myscore, :pic_attributes=> {} ])
    end
end

app/helpers/newscores_helper.rb
module NewscoresHelper
end

app/views/newscores/_form.html.erb
<p>pour faire : <p>
<p><a href="/mynewscore/aa/lily-c1aa7316.ly">
  <img align="middle"
       border="0"
       src="/mynewscore/aa/lily-c1aa7316.png"
       alt="[image of music]"></a></p>

<%= form_with(model: newscore) do |form| %>
  <% if newscore.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(newscore.errors.count, "error") %> prohibited this newscore from being saved:</h2>

      <ul>
        <% newscore.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :composer, style: "display: block" %>
    <%= form.text_field :composer %>
  </div>

  <div>
    <%= form.label :toplevelmarkup, style: "display: block" %>
    <%= form.text_field :toplevelmarkup %>
  </div>

  <div>
    <%= form.label :metronomemark, style: "display: block" %>
    <%= form.text_field :metronomemark %>
  </div>

  <div>
    <%= form.label :textmark, style: "display: block" %>
    <%= form.text_field :textmark %>
  </div>

  <div>
    <%= form.label :accord, "accord (a, b, c, d , e ou f)", style: "display: block" %>
    <%= form.text_field :accord %>
  </div>
  <div>
    <%= form.label :cmajorsevensymbol, style: "display: block" %>
    <%= form.text_field :cmajorsevensymbol %>
  </div>

  <div>
    <%= form.label :testscript, style: "display: block" %>
    <%= form.text_field :testscript %>
  </div>

  <div>
    <%= form.label :notehead, style: "display: block" %>
    <%= form.text_field :notehead %>
  </div>

  <div>
    <%= form.label :fingering, style: "display: block" %>
    <%= form.text_field :fingering %>
  </div>

  <div>
    <%= form.label :notehead, style: "display: block" %>
    <%= form.text_field :notehead %>
  </div>

  <div>
    <%= form.label :rest, style: "display: block" %>
    <%= form.text_field :rest %>
  </div>

  <div>
    <%= form.label :tuplenumber, style: "display: block" %>
    <%= form.text_field :tuplenumber %>
  </div>

  <div>
    <%= form.label :lyrictext, style: "display: block" %>
    <%= form.text_field :lyrictext %>
  </div>

  <div>
    <%= form.label :dynamictext, style: "display: block" %>
    <%= form.text_field :dynamictext %>
  </div>

  <div>
    <%= form.label :key_signature, style: "display: block" %>
    <%= form.text_field :key_signature %>
  </div>

  <div>
    <%= form.label :time_signature, style: "display: block" %>
    <%= form.text_field :time_signature %>
  </div>
  <div>
    <%= form.label :myscore, style: "display: block" %>
    <%= form.text_area :myscore, style: "width:100%;height: 500px;" %>
  </div>
<%=form.fields_for :pic do |f|%>
  <div>
    <%= f.label :mypic, style: "display: block" %>
    <%= f.file_field :mypic %>
  </div>
<%end%>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/newscores/_newscore.html.erb
<div id="<%= dom_id newscore %>">
  <p>
    <strong>Title:</strong>
    <%= newscore.title %>
  </p>

  <p>
    <strong>Composer:</strong>
    <%= newscore.composer %>
  </p>

  <p>
    <strong>Toplevelmarkup:</strong>
    <%= newscore.toplevelmarkup %>
  </p>

  <p>
    <strong>Metronomemark:</strong>
    <%= newscore.metronomemark %>
  </p>

  <p>
    <strong>Textmark:</strong>
    <%= newscore.textmark %>
  </p>

  <p>
    <strong>Cmajorsevensymbol:</strong>
    <%= newscore.cmajorsevensymbol %>
  </p>

  <p>
    <strong>Testscript:</strong>
    <%= newscore.testscript %>
  </p>

  <p>
    <strong>Notehead:</strong>
    <%= newscore.notehead %>
  </p>

  <p>
    <strong>Fingering:</strong>
    <%= newscore.fingering %>
  </p>

  <p>
    <strong>Notehead:</strong>
    <%= newscore.notehead %>
  </p>

  <p>
    <strong>Rest:</strong>
    <%= newscore.rest %>
  </p>

  <p>
    <strong>Tuplenumber:</strong>
    <%= newscore.tuplenumber %>
  </p>

  <p>
    <strong>Lyrictext:</strong>
    <%= newscore.lyrictext %>
  </p>

  <p>
    <strong>Dynamictext:</strong>
    <%= newscore.dynamictext %>
  </p>

  <p>
    <strong>Key signature:</strong>
    <%= newscore.key_signature %>
  </p>

  <p>
    <strong>Time signature:</strong>
    <%= newscore.time_signature %>
  </p>

</div>

app/views/newscores/createscore.html.erb
<%=content_for :hey do%>
<%if @newscore.pic.try(:mypic)%>
<style>
body {
background: url("/uploads/<%=@newscore.pic.try(:mypic)%>");
}
</style>
<%end%>
<%end%>

<h1>
<%=@newscore.title%>

</h1>
<iframe src="/uploads/<%=@hi%>/hey<%=@hi%>" style="width:100%;height:500px;">
</iframe>
<%=link_to "retour a la partition", newscore_path(@newscore)%>
<%=link_to "voir la partition", seescore_newscore_path(@newscore)%>

app/views/newscores/edit.html.erb
<% content_for :title, "Editing newscore" %>

<h1>Editing newscore</h1>

<%= render "form", newscore: @newscore %>

<br>

<div>
  <%= link_to "Show this newscore", @newscore %> |
  <%= link_to "Back to newscores", newscores_path %>
</div>

app/views/newscores/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Newscores" %>

<h1>Newscores</h1>

<div id="newscores">
  <% @newscores.each do |newscore| %>
    <%= render newscore %>
    <p>
      <%= link_to "Show this newscore", newscore %>
    </p>
  <% end %>
</div>

<%= link_to "New newscore", new_newscore_path %>

app/views/newscores/new.html.erb
<% content_for :title, "New newscore" %>

<h1>New newscore</h1>

<%= render "form", newscore: @newscore %>

<br>

<div>
  <%= link_to "Back to newscores", newscores_path %>
</div>

app/views/newscores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @newscore %>

<div>
<%=link_to "voir la partition", seescore_newscore_path(@newscore)%>

  <%= link_to "add a pic to this new score", addpic_newscore_path(@newscore) %> |
  <%= link_to "create a	 score for this new score", createscore_newscore_path(@newscore) %> |
  <%= link_to "Edit this newscore", edit_newscore_path(@newscore) %> |
  <%= link_to "Back to newscores", newscores_path %>

  <%= button_to "Destroy this newscore", @newscore, method: :delete %>
</div>