config/routes.rb
Rails.application.routes.draw do
  get "welcome/search"
  post "welcome/song"
  resources :pics
  resources :newscores do
   member do
    get "seescore"
    get "createscore"
    get "addpic"
   end
  end
  resources :fragments do
   member do
    get "createscore"
    get "seescore"
   end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "fragments#index"
end

app/models/fragment.rb
class Fragment < ApplicationRecord
def key_signature=(hey)
write_attribute(:key_signature, hey.downcase.gsub("♯", "is").gsub("♭", "es"))
end
def time_signature=(hey)
write_attribute(:time_signature, hey.downcase.gsub(" beats per bar", "/4"))
end
def tempo=(hey)
if hey.include?("BPM")
x=hey.gsub(" BPM", "")
write_attribute(:tempo, "4 = "+x.strip.squish)
else
write_attribute(:tempo, hey)
end
end

end

app/controllers/fragments_controller.rb
class FragmentsController < ApplicationController
  before_action :set_fragment, only: %i[ show edit update destroy createscore seescore]

  def seescore
      hi=(@fragment.title+@fragment.id.to_s).parameterize
      @hi=hi

      render :createscore
  end

  # GET /fragments or /fragments.json
  def createscore
      @score="
      
      <lilypond fragment staffsize=26>
        \\key #{@fragment.key_signature.sub(" "," \\")}
        \\numericTimeSignature
        \\time #{@fragment.time_signature}
        \\tempo #{@fragment.tempo}
        
        #(make-dynamic-script \#{ \\markup { \\dynamic #{@fragment.nuance} \\normal-text \\italic \\bold #{@fragment.caractere} } \#}) #{@fragment.myscore} d' e' f' g'2 g'
      </lilypond>
      "
      
      p @score
      
      wow="./public/uploads/"
      hi=(@fragment.title+@fragment.id.to_s).parameterize
      @hi=hi
      p wow+hi
      File.write(wow+"hey"+hi+".html", @score)
      @hey=`(cd #{wow} && lilypond-book hey#{hi}.html -f html --output #{hi})`

  end
  def index
    @fragments = Fragment.all
  end

  # GET /fragments/1 or /fragments/1.json
  def show
  end

  # GET /fragments/new
  def new
    @fragment = Fragment.new
  end

  # GET /fragments/1/edit
  def edit
  end

  # POST /fragments or /fragments.json
  def create
    @fragment = Fragment.new(fragment_params)

    respond_to do |format|
      if @fragment.save
        format.html { redirect_to @fragment, notice: "Fragment was successfully created." }
        format.json { render :show, status: :created, location: @fragment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fragment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fragments/1 or /fragments/1.json
  def update
    respond_to do |format|
      if @fragment.update(fragment_params)
        format.html { redirect_to @fragment, notice: "Fragment was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @fragment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fragment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fragments/1 or /fragments/1.json
  def destroy
    @fragment.destroy!

    respond_to do |format|
      format.html { redirect_to fragments_path, notice: "Fragment was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fragment
      @fragment = Fragment.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def fragment_params
      params.expect(fragment: [ :clef, :nuance, :key_signature, :time_signature, :caractere, :tempo, :title, :myscore ])
    end
end

app/helpers/fragments_helper.rb
module FragmentsHelper
end

app/views/fragments/_form.html.erb
<%= form_with(model: fragment) do |form| %>
  <% if fragment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fragment.errors.count, "error") %> prohibited this fragment from being saved:</h2>

      <ul>
        <% fragment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :clef, style: "display: block" %> g, f
    <%= form.text_field :clef, placeholder: "clef: g, f" %>
  </div>

  <div>
    <%= form.label :nuance, style: "display: block" %> 
<p>\ppppp, \pppp, \ppp, \pp, \p, \mp, \mf, \f, \ff, \fff, \ffff, \fffff, \fp, \sf, \sff, \sp, \spp, \sfz, \rfzet \n

 et tu peux mélanger texte et nuance piuF = \markup { \italic più \dynamic f }
<br>

\layout { ragged-right = ##f }

\relative c'' {
  c2\f c-\piuF
}</p>
<p><a href="/scoreform/7c/lily-fbc128a2.ly">
  <img align="middle"
       border="0"
       src="/scoreform/7c/lily-fbc128a2.png"
       alt="[image of music]"></a></p>
<p>la nuance et le caractere


    \markup {
      \column {
        \line {
          \concat { 1 \super st }
          movement
        }
        \line {
          \concat { \dynamic p , }
          \italic { con dolce espressione }
        }
      }
    }
</p>
<p><a href="/scoreform/8f/lily-ea85f6e4.ly">
  <img align="middle"
       border="0"
       src="/scoreform/8f/lily-ea85f6e4.png"
       alt="[image of music]"></a></p>
    <%= form.text_field :nuance, placeholder: "nuance" %>
  </div>

  <div>
    <%= form.label :key_signature, style: "display: block" %> c major, d minor, f major etc.
<p><a href="/scoreform/f9/lily-7cc64a7f.ly">
  <img align="middle"
       border="0"
       src="/scoreform/f9/lily-7cc64a7f.png"
       alt="[image of music]"></a></p>
<p><a href="/scoreform/f4/lily-5d4a28dc.ly">
  <img align="middle"
       border="0"
       src="/scoreform/f4/lily-5d4a28dc.png"
       alt="[image of music]"></a></p>
<p><a href="/scoreform/eb/lily-83409d15.ly">
  <img align="middle"
       border="0"
       src="/scoreform/eb/lily-83409d15.png"
       alt="[image of music]"></a></p>
    <%= form.text_field :key_signature, placeholder: "g major, f major" %>
  </div>

  <div>
    <%= form.label :time_signature, style: "display: block" %>
 4/4, 3/4, 6/8C, etc.
<p><a href="/scoreform/00/lily-69f0cefb.ly">
  <img align="middle"
       border="0"
       src="/scoreform/00/lily-69f0cefb.png"
       alt="[image of music]"></a></p>
<p><a href="/scoreform/46/lily-520ebb9f.ly">
  <img align="middle"
       border="0"
       src="/scoreform/46/lily-520ebb9f.png"
       alt="[image of music]"></a></p>
    <%= form.text_field :time_signature, placeholder: "4/4, 3/4" %>
  </div>

  <div>
    <%= form.label :caractere, style: "display: block"%>

<p>
    \markup {
      \column {
        \line {
          \concat { 1 \super st }
          movement
        }
        \line {
          \concat { \dynamic p , }
          \italic { con dolce espressione }
        }
      }
    }

</p>
<p>
"Terme italien 
affettuoso 
agitato 
amabile 
amoroso 
appassionato 
ardito 
brillante 
cantabile 
capriccioso 
comodo 
con allegrezza 
con anima 
con bravura 
con brio 
con delicatezza 
con dolore 
con espressione 
con fuoco 
con grazia 
con gusto 
con moto 
con spirito 
con tenerezza 
delicatamente 
delicato 
disperato 
dolce 
dolcissimo 
doloroso 
drammatico 
energico 
espressivo 
furioso 
giocoso 
grazioso 
imperioso 
lagrimoso 
leggero 
maestoso 
malinconico 
mesto 
nobile 
patetico 
pomposo 
religioso 
risoluto 
rustico 
scherzando 
semplice 
teneramente 
tranquillo 
tristamente

</p>
<p>
 #(make-dynamic-script #{ \markup { \dynamic mp \normal-text \italic \bold dolce } #}) 
</p>
<p><a href="/scoreform/35/lily-05051c89.ly">
  <img align="middle"
       border="0"
       src="/scoreform/35/lily-05051c89.png"
       alt="[image of music]"></a></p>

    <%= form.text_field :caractere, placeholder: "giocoso, grazioso,  imperioso " %>
  </div>

  <div>
    <%= form.label :tempo, style: "display: block" %>
<p><a href="/scoreform/a4/lily-f57ec71f.ly">
  <img align="middle"
       border="0"
       src="/scoreform/a4/lily-f57ec71f.png"
       alt="[image of music]"></a></p>
Prestissimo, Vivace, "Andante", and "Largo" "Allegro" 4 = 100 (la noire à 100bpm)
    <%= form.text_field :tempo, placeholder: "Adagio , Allegro, Presto" %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, placeholder: "titre de ma musique" %>
  </div>

  <div>
    <%= form.label :myscore, style: "display: block" %>
    <%= form.text_area :myscore, placeholder: "%en avant la musique", style: "width: 100%;height:600px;" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/fragments/_fragment.html.erb
<div id="<%= dom_id fragment %>">
  <p>
    <strong>Clef:</strong>
    <%= fragment.clef %>
  </p>

  <p>
    <strong>Nuance:</strong>
    <%= fragment.nuance %>
  </p>

  <p>
    <strong>Key signature:</strong>
    <%= fragment.key_signature %>
  </p>

  <p>
    <strong>Time signature:</strong>
    <%= fragment.time_signature %>
  </p>

  <p>
    <strong>Caractere:</strong>
    <%= fragment.caractere %>
  </p>

  <p>
    <strong>Tempo:</strong>
    <%= fragment.tempo %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= fragment.title %>
  </p>

  <p>
    <strong>Myscore:</strong>
    <%= fragment.myscore %>
  </p>

</div>

app/views/fragments/createscore.html.erb
<h1>
<%=@fragment.title%>

</h1>
<iframe src="/uploads/<%=@hi%>/hey<%=@hi%>" style="width:100%;height:500px;">
</iframe>
<%=link_to "retour a la partition", fragment_path(@fragment)%>

app/views/fragments/edit.html.erb
<% content_for :title, "Editing fragment" %>

<h1>Editing fragment</h1>

<%= render "form", fragment: @fragment %>

<br>

<div>
  <%= link_to "Show this fragment", @fragment %> |
  <%= link_to "Back to fragments", fragments_path %>
</div>

app/views/fragments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Fragments" %>

<h1>Fragments</h1>

<div id="fragments">
  <% @fragments.each do |fragment| %>
    <%= render fragment %>
    <p>
      <%= link_to "Show this fragment", fragment %>
    </p>
  <% end %>
</div>

<%= link_to "New fragment", new_fragment_path %>

app/views/fragments/new.html.erb
<% content_for :title, "New fragment" %>

<h1>New fragment</h1>

<%= render "form", fragment: @fragment %>

<br>

<div>
  <%= link_to "Back to fragments", fragments_path %>
</div>

app/views/fragments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @fragment %>

<div>
<%=link_to "voir la partition", seescore_fragment_path(@fragment)%>

  <%= link_to "Edit this fragment", edit_fragment_path(@fragment) %> |
  <%= link_to "create score of this fragment", createscore_fragment_path(@fragment) %> |
  <%= link_to "Back to fragments", fragments_path %>

  <%= button_to "Destroy this fragment", @fragment, method: :delete %>
</div>